name: CMake

on: [push, pull_request]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build-windows-Gocq:
    strategy:
      fail-fast: false
      matrix:
        include:
        - type: x64
          triplet: x64-windows-static
          
    runs-on: windows-2022
    
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Create Build Environment
      # Some projects don't allow in-source building, so create a separate build directory
      # We'll use this as our working directory for all subsequent commands
      run: cmake -E make_directory ${{github.workspace}}/build
      
    - name: Cache
      uses: actions/cache@v2.1.4
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: ${{github.workspace}}/build/vcpkg_installed
        # An explicit key for restoring and saving the cache
        key: ${{ runner.os }}-${{ matrix.triplet }}-${{ hashFiles('**/vcpkg.json') }}
        restore-keys:  ${{ runner.os }}-${{ matrix.triplet }}-

    - name: Setup Vcpkg
      shell: cmd
      working-directory: ${{github.workspace}}/vcpkg
      run: bootstrap-vcpkg.bat

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      # Note the current convention is to use the -S and -B options here to specify source 
      # and build directories, but this is only available with CMake 3.13 and higher.  
      # The CMake binaries on the Github Actions machines are (as of this writing) 3.12
      run: cmake $GITHUB_WORKSPACE -A ${{ matrix.type }} -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DVCPKG_TARGET_TRIPLET=${{ matrix.triplet }}

    - name: Build
      shell: bash
      working-directory: ${{github.workspace}}/build
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: cmake --build . --config $BUILD_TYPE

    - name: Test
      shell: bash
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C $BUILD_TYPE
      
    - name: Upload
      uses: actions/upload-artifact@v2.2.2
      with:
        # Artifact name
        name: ${{ matrix.triplet }}-Gocq
        # A file, directory or wildcard pattern that describes what to upload
        path: "**/DiceMaid-Gocq.exe"